# Generated by Django 4.2.1 on 2023-06-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='app_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='app_user',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
