# Generated by Django 4.2.1 on 2023-07-03 00:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='header',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
